---
abstract: 'XML producer from humane perl data, parser to base perl data and simple XPath'
author:
  - 'Nick Kostirya <nick@ToDo.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Perl
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Parser: 0
version: 0.06
